### ISSUE TITLE
Login Screen Freezing 

### ISSUE THREAD

**Issue by samvid2020** [bhattabhi013/Vritant#1]
I tried to log in to the Application but the page freezes which makes the user unable to login 

![image](https://user-images.githubusercontent.com/83578700/210408782-829aad95-c187-47bf-9616-e7d54d738932.png)

**Comment by bhattabhi013** [comment]
Hi @samvid2020,
Thanks for raising the issue.
I'm going to remove the Google sign-in during the development phase, so that all users can work on it without any issues.

**Comment by bhattabhi013** [comment]
Hi @samvid2020,
I've removed the Google Login, now you can access the code.
However, this is only a temporary solution and will be Google login will be re-implemented after we find a solution.
