### ISSUE TITLE
Page not found error after clicking on contributing,

### ISSUE THREAD

**Issue by bhattabhi013** [bhattabhi013/Vritant#11]
What:
Error 404 after clicking on Contributing heading on `README.md`.

Screenshot:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/47862474/216766181-675524ea-f110-4636-949f-521c6569bc4c.png">

**Comment by Soumya-Kushwaha** [comment]
There is no section called 'Contributing'.
Where do you want the page to exactly scroll to when clicked?

**Comment by bhattabhi013** [comment]
I suggest removing it from there as we already have a 'how to contribute' section.
What do you suggest?

**Comment by Soumya-Kushwaha** [comment]
Done via #12
