### ISSUE TITLE
Adding Google SignIn Properly

### ISSUE THREAD

**Issue by Perumallpardhiv** [bhattabhi013/Vritant#15]
In this, it is not showing Google SignIn option before the main screen of app.

Video Reference :

https://user-images.githubusercontent.com/96647299/218194474-8555ed6a-f46d-4718-84fe-64ed14d33456.mp4

**Comment by Perumallpardhiv** [comment]
@bhattabhi013
I can solve this issue.

**Comment by bhattabhi013** [comment]
HI @Perumallpardhiv,
Thanks for creating the issue, however, this functionality is already available.
I've just commented on the code to skip the issue. please refer #1 .
However, this is only a temporary solution, and Google login will be re-implemented after we find a solution.
