### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by A91y** [bhattabhi013/Vritant#19]
These files can be added to project for better code structure.

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by bhattabhi013** [comment]
Sure, assigning it to you.

**Comment by A91y** [comment]
Please merge and close this issue if everything is fine.

**Comment by dhruv-porwal** [comment]
Hey I am a newbie open source contributor pls assign this issue to me under iwoc

**Comment by A91y** [comment]
@dhruv-porwal Issue is already solved in the PR attached. Only merging is awaited.
Best of luck for your future contributions Dhruv 👍.

**Comment by bhattabhi013** [comment]
Completed by #20 .
