### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by bhattabhi013** [bhattabhi013/Vritant#2]
Add issue template for the project.

**Comment by Aman-Singh-Kushwaha** [comment]
I can do this please assign it to me

**Comment by Aman-Singh-Kushwaha** [comment]
Please do tell me if you want a specific label other than [Feature Request] , [Bug Report]

**Comment by bhattabhi013** [comment]
Hi @Aman-Singh-Kushwaha,
No, but please include 'screenshots' and 'how to replicate error' sections in your template

**Comment by Ghat0tkach** [comment]
@bhattabhi013 i would love to work on this issue as part of gssoc 23

**Comment by fizakhan90** [comment]
Can you assign it to me under gssoc'23?

**Comment by bhattabhi013** [comment]
Sure @fizakhan90, assigning it to you.

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇

**Comment by shaileshthakur1** [comment]
Abhishek Bhaiya ..Please assign this issue to me ? I ma wanting to work over it please. @bhattabhi013

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by bhattabhi013** [comment]
Sure @sagnik-p,
Assigning it to you.
Please read the thread to get more clarity about the requirements.

**Comment by bhattabhi013** [comment]
Fixed by #47
