### ISSUE TITLE
🧑‍💻 Add Contributors and Admin Details with extra info.

### ISSUE THREAD

**Issue by Suryansh1720001** [bhattabhi013/Vritant#21]
Hello @bhattabhi013 
**Is your feature request related to a problem? Please describe.**
### Features that I want to add in README FILE

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by bhattabhi013** [comment]
Sure, go ahead.
