### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by Bharadwajshivam28** [bhattabhi013/Vritant#22]
I want to add PROCESS of project, WORKFLOW of project and AIM of project in README FILE

**Comment by Bharadwajshivam28** [comment]
@bhattabhi013

**Comment by bhattabhi013** [comment]
Hi @Bharadwajshivam28,
Can you be more specific?
How are you going to add a process or workflow?

**Comment by Bharadwajshivam28** [comment]
> Hi @Bharadwajshivam28,
> Can you be more specific?
> How are you going to add a process or workflow? 
> 
> 

Sir basically in readme file how the project is working, process of project and  aim behind the project

**Comment by bhattabhi013** [comment]
Sure, go ahead.
Assigning it to you.

**Comment by Bharadwajshivam28** [comment]
> Sure, go ahead.
> Assigning it to you.

Ok sir thanks 🙏

**Comment by Bharadwajshivam28** [comment]
close this one sir @bhattabhi013

**Comment by Bharadwajshivam28** [comment]
it is completed sir so close it

**Comment by bhattabhi013** [comment]
Closed by #23

**Comment by Bharadwajshivam28** [comment]
thanks sir
