### ISSUE TITLE
Prevent screen from getting dim.

### ISSUE THREAD

**Issue by dhruv-porwal** [bhattabhi013/Vritant#26]
Mobile screen may get dim whenever user may not respond to a request intentionally/unintenionally. This may also happen when screen gets hanged due to some system interrupt or asynchronous process. This needs to be stopped.

**Comment by dhruv-porwal** [comment]
kindly assign this issue to me.

**Comment by bhattabhi013** [comment]
Sure @dhruv-porwal.

**Comment by bhattabhi013** [comment]
Closed by #27
