### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by bhattabhi013** [bhattabhi013/Vritant#3]
Add PR template for the project.

**Comment by Aman-Singh-Kushwaha** [comment]
I can do this please assign it to me

**Comment by Aman-Singh-Kushwaha** [comment]
![image](https://user-images.githubusercontent.com/96011814/212262420-33aa9894-15a4-49bf-b5a6-05364eb2aa59.png)

Do you think this Template will work? 
Do you have any change proposals?
Also, I apologise for being late

**Comment by prathna17** [comment]
Can I do this task?

**Comment by bhattabhi013** [comment]
Hi @prathna17,
You can work ok any other issue as this is already assigned.

**Comment by bhattabhi013** [comment]
Closed via #6
