### ISSUE TITLE
Adding an onboarding experience for new users

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#44]
**Is your feature request related to a problem? Please describe.**
I'd add the onboarding flow to the app that would make the users get familiar with the application fairly easily and make them understand how to use the application. 

**Describe the solution you'd like**
I'd design and implement the intro screens along with proper onboarding, so that when the app would be installed and opened for the first time, the users would be greeted by an automated experience which would acquaint users with app's features and how to use it.

**Comment by jaivsh** [comment]
@bhattabhi013 Greetings sir, I'd add an onboarding experience discussed above, so can you please assign this task for me please?

**Comment by bhattabhi013** [comment]
Hi @jaivsh,
Thanks sound like a great functionality to add.
You can start working on it.

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by bhattabhi013** [comment]
HI @jaivsh,
Are you still working on it?

**Comment by jaivsh** [comment]
Hi @bhattabhi013 , yup, just a day more. Gonna pull tomorrow!! Sorry for not informing in advance!
