### ISSUE TITLE
Reducing code repetition in lib/Home/screens.dart file

### ISSUE THREAD

**Issue by Shivansh1212** [bhattabhi013/Vritant#45]
Can make a separate stateless widget and call it whenever the container is required as same properties are called again. This can reduce the size of file and increase its readability.
@bhattabhi013, kindly assign this issue to me under GSSoC 23.

**Comment by bhattabhi013** [comment]
Hi @Shivansh1212,
This is a great idea but can you be a bit more specific about the widget you are talking about?

**Comment by Shivansh1212** [comment]
@bhattabhi013, I am talking about the similar containers which are having same properties (apart from different GIFs used) that are repeatedly used in the mentioned file. I can make a separate class or a function(not a widget, sorry) and call it whenever required performing exactly the same task but taking less lines of code. I hope you understand now.

**Comment by bhattabhi013** [comment]
Sure, assigning it to you.

**Comment by tanishgoyal07** [comment]
Hey, please assign this issue to me
