### ISSUE TITLE
Video Player in Readme

### ISSUE THREAD

**Issue by Pratik-11** [bhattabhi013/Vritant#52]
Hi Currently i am roaming around the project and its my first proposal and its quite basic.

### I tend to improve the docs a bit by adding the video play in readme realtime functionality by adding the embedd video with some HTML

- Kindly assign this to me under GSSoc 2023
- thanks

**Comment by bhattabhi013** [comment]
Sure, assigning it to you.

**Comment by Pratik-11** [comment]
#54

**Comment by bhattabhi013** [comment]
Fixed via #54
