### ISSUE TITLE
[DOCS] <Modifications in Read me>

### ISSUE THREAD

**Issue by iqrafirdose** [bhattabhi013/Vritant#59]
### Description

As Read Me is an important part of any project, with read me, we can able to know what the project is all about.

In Read Me, There is no paragraph about the project Vritant. I will add a paragraph that shows what vritant is.

And I will add the logo(amazing logo of vritant) of Vritant before the name of the Vritant.

There is no code_of_conduct file and the license is added in the Read me file. I will add that.

There are some typo mistakes in read me, I will correct it.

### Screenshots

![g12](https://github.com/bhattabhi013/Vritant/assets/114678694/dd6ab641-20bb-466d-9a1a-87b3b32dc3d7)

**Comment by iqrafirdose** [comment]
Can you please assign the issue to me under gssoc?

**Comment by iqrafirdose** [comment]
Hello @bhattabhi013 , Can you please check this issue?

**Comment by bhattabhi013** [comment]
Hi, 
Most of the things you mentioned are already there in the project. (Photograph, Paragraph, and working).
However, If you want to fix some typos feel free to do them.

**Comment by iqrafirdose** [comment]
Hello @bhattabhi013 can you please tell me the spelling of Vritant or Vritaant? Because in screenshots the spelling is vritaant but in the repo it is vritant.

**Comment by bhattabhi013** [comment]
Hi @iqrafirdose,
The name of the project is Vritant.

**Comment by bhattabhi013** [comment]
> Hi @iqrafirdose, The name of the project is Vritant.

Edit: Name is Vritaant.

Closed by #65

**Comment by iqrafirdose** [comment]
Hello @bhattabhi013, I am contributing to GSSOC. So, can you please make this under GSSOC?
