### ISSUE TITLE
Add CodeQL workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [bhattabhi013/Vritant#60]
### Description

Add the codeql analysis workflow to be run on every push and pull request to prevent any security vulnerabilities in the codebase.

I would like to work on this as a part of GSSoC 23.

**Comment by bhattabhi013** [comment]
What workflow do you suggest?

**Comment by metabiswadeep** [comment]
@bhattabhi013 I suggest the codeql workflow. I can start working on it as soon as you assign me the issue.

**Comment by bhattabhi013** [comment]
Assigning it to you @metabiswadeep
