### ISSUE TITLE
Feature Request: Designing a website for "Vritant"

### ISSUE THREAD

**Issue by yaten2302** [bhattabhi013/Vritant#61]
### Description

Hi @bhattabhi013, I was having an idea of designing a website for "Vritant".

Here all the details of this app will be added with some demo screenshots, videos, features and some description about the app.
Also there can be a "Contact page" and "FAQs section". This will be easier for the user to get to know about the project very easily.

Also it will attract more users because of the beautiful UI of the website and the app.

Please assign this task to me under GSSOC'23, as I want to work on this issue 🙏🙏

**Comment by bhattabhi013** [comment]
Sure,
You can start working on it.

**Comment by yaten2302** [comment]
Hi @bhattabhi013, could you please send some screenshots of the app and your socials so that I can put them in the website.
