### ISSUE TITLE
[FEATURE] Share App and rhymes feature in homepage.

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#63]
### Description

I'd implement a share the application feature in the homepage, along with a share rhymes feature in the individual rhymes section. This would launch a share intent that would share application and rhymes to wider potential users. 

 

### Screenshots

![image](https://github.com/bhattabhi013/Vritant/assets/93859359/12338bc7-c56e-4184-a688-18d480773aa1)

### Additional information

For this, I plan to use the following libraries:
- shared_preferences
- share_plus

**Comment by jaivsh** [comment]
@bhattabhi013 can u please assign to me this issue please?

**Comment by bhattabhi013** [comment]
Hi, 
Assigning it to you🚀
