### ISSUE TITLE
Fix "TODO: Handle exception null" toast bug in home page

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#64]
### Description

In homepage, if the google play services is not installed in a device, the app is presenting to that user a toast bug which doesnt wanishes by itself on the home screen, as shown in the screnshot. I'd handle this bug and would replace it with a single time appearing info message to the end user, along with the proper steps to be taken for google play services sign in in vritant. 

### Screenshots

![Screenshot_20230711_010403](https://github.com/bhattabhi013/Vritant/assets/93859359/df48e191-8d0f-428a-ad7a-e689b924eb53)

**Comment by AbhiSharma1511** [comment]
hey @jaivsh I am a android flutter developer. I want to work on this.

**Comment by bhattabhi013** [comment]
Hi @jaivsh,
Google Sign-in is already there in the application.
However, I've disabled it temporarily for some time and if you want to fix the null exception issue, you can comment out that code.
