### ISSUE TITLE
[DOCS] adding the "Techstack "and "connect with me" section along with badges in the readme

### ISSUE THREAD

**Issue by 1Shubham7** [bhattabhi013/Vritant#67]
### Description

We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.

Similarly, for Techstack

### Additional information

Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by bhattabhi013** [comment]
Hi @1Shubham7,
I don't think this is required. You can work on some other issues.
