### ISSUE TITLE
[FEATURE] Adding more setting options in Settings screen

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#69]
### Description

The Settings Screen of the application currently has only 1 setting option: the share app option. I'd add more setting options to the app, such as 
- Turning notifications on or off
- Language
- Support Development: This would bring users to the Vritant repository's issues section, highlighting concerning issues to contribute to. 

### Screenshots

![Screenshot_20230730_074015](https://github.com/bhattabhi013/Vritant/assets/93859359/c8c5b475-3c18-4bc2-a37a-e6aea6b0e11e)

**Comment by jaivsh** [comment]
@bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Hi @jaivsh,
There is no functionality to send notifications or language changes but I think you can add the support development part.
