### ISSUE TITLE
Null on login page

### ISSUE THREAD

**Issue by bhattabhi013** [bhattabhi013/Vritant#7]
What:
Add a meaningful message instead of null.

Where:
On home page

Screenshot:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/47862474/213912135-ea6ce3d1-dd01-4e47-b27e-22b8a7f0e9e6.png">

**Comment by Yashs1623** [comment]
I can contribute on this issue, can you please assign it to me

**Comment by bhattabhi013** [comment]
Sure @Yashs1623,
Assigning it to you.

**Comment by MansiBhayade** [comment]
Can you please assign this issue to me

**Comment by bhattabhi013** [comment]
Hi @MansiBhayade,
You can work on some other issue as this issue is already assigned to @Yashs1623.
You can create new issues as well.

**Comment by Yashs1623** [comment]
# Added a meaningful message

I have created a pull request on this issue, please check it
![meaningful_message](https://user-images.githubusercontent.com/80099005/217259731-669cccdb-69e4-401f-90cd-d38dc087fe1d.jpg)

I can change it to a user name when firebase login is implemented
