### ISSUE TITLE
[FEATURE] Creating a Contact-Us screen in the application

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#70]
### Description

I'd create a contact-us screen, where the users would be presented with a form to fill in, and the responses would be sent to a secured Google sheet, where all responses would be listed down, along with user's email and timestamp to differentiate between the entries. I'd do the integration of google sheets with the app via Sheets API. 

### Screenshots
![h](https://github.com/bhattabhi013/Vritant/assets/93859359/4954e205-8782-42ea-a107-6b4fa87f6539)

### Additional information

Google sheets api: https://developers.google.com/sheets/api/guides/concepts

**Comment by jaivsh** [comment]
Hi @bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Hi @jaivsh,
Assigning it to you.
