### ISSUE TITLE
[FEATURE] Adding Dark Mode for the app

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#71]
### Description

I'd add a dark-mode for the application, along with a switch option in the settings, through which the users would be able to switch between the dark and the light mode in the application. 

### Screenshots

![image](https://github.com/bhattabhi013/Vritant/assets/93859359/f0efac79-6b18-4f14-bf64-e5db965173d4)

**Comment by jaivsh** [comment]
@bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Sure

**Comment by jaivsh** [comment]
@bhattabhi013 check this PR
