### ISSUE TITLE
[FEATURE] Adding a Licenses screen for the application

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#72]
### Description

I'd add a licenses screen, which would be able to display all the app's licenses along with the licenses of all the plugins used in the application. It would be accessable via Settings Screen and would be present as a settings option.

### Screenshots

![image](https://github.com/bhattabhi013/Vritant/assets/93859359/7986efd8-9e62-415a-9cce-3fc984b0988a)

**Comment by jaivsh** [comment]
@bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Sure, assigning it to you.

**Comment by jaivsh** [comment]
@bhattabhi013 check this PR
