### ISSUE TITLE
[FEATURE] Adding a FAQ section with relevant FAQs for users

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#74]
### Description

I'd add an FAQ section in the application with all the relevant questions and solutions in an accordion dropdown template in flutter. Along with this, i'd also add a search bar on top which would search and filter the relevant questions.

### Screenshots

![image](https://github.com/bhattabhi013/Vritant/assets/93859359/5388f39b-5ce7-4a65-9313-3b71a9596a89)

**Comment by jaivsh** [comment]
@bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Sure, assigning it to you.
However, what content are you going to add in `FAQ`?
