### ISSUE TITLE
[DOCS] Missing Guidelines for git commit messages in Contribution.md. ✨

### ISSUE THREAD

**Issue by Nishitbaria** [bhattabhi013/Vritant#87]
### Description

As a project that values clear and consistent commit messages, we should adopt the Conventional Commits guideline to enhance our development workflow and improve collaboration among contributors. Conventional Commits provide a well-defined specification for writing commit messages, making it easier to understand the purpose and impact of each commit.

### Screenshots

N/A

### Additional information

**By implementing the Conventional Commits guideline, our project will enjoy the following benefits:**

Clear and Meaningful Commit Messages: Contributors will be encouraged to provide descriptive commit messages that explain the purpose and changes introduced in each commit, making it easier for everyone to follow the development history.
Automated Release Notes: Conventional Commits can be utilized to generate automated release notes, making the release process more efficient and less error-prone.
Improved Collaboration: The standardized commit messages will enhance communication and collaboration among contributors and maintainers, fostering a healthier development community.
Easier Changelog Generation: Following the Conventional Commits specification will simplify the generation of changelogs, which is crucial for users and stakeholders to track project changes.

**Comment by bhattabhi013** [comment]
Sure, go ahead @Nishitbaria
