### ISSUE TITLE
Bugs in settings.dart 

### ISSUE THREAD

**Issue by Touseef-md** [bhattabhi013/Vritant#91]
### Description

You need to create the constructor for settingspagestate class and there are some other bugs as well.

 

### Screenshots

![image](https://github.com/bhattabhi013/Vritant/assets/79767012/b453c3ef-2d31-4dc5-b66e-d38d5e6d5ee7)

**Comment by Touseef-md** [comment]
Hey @bhattabhi013, please assign this to me.

**Comment by bhattabhi013** [comment]
Hi assigning it to you, but before working on it, please list down all the bugs that you are facing.
It might help others in the community.

**Comment by bhattabhi013** [comment]
Resolved in the new commit🚀
